name: connect_me
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  faker: ^2.1.0
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  flutter_speed_dial: ^7.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  googleapis: ^12.0.0
  icons_plus: ^4.0.0
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  rename: ^3.0.1
  searchbar_animation: ^0.0.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  status_view: ^0.0.2
  timeago: ^3.6.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
