name: connect_me
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  animated_custom_dropdown: ^2.0.0
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.3.0
  clipboard: ^0.1.3
  cloud_firestore: ^4.13.5
  country_code_picker: ^3.0.0
  csc_picker: ^0.2.7
  dartz: ^0.10.1
  equatable: ^2.0.5
  expandable: ^5.0.1
  faker: ^2.1.0
  firebase_analytics: ^10.7.4
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.6
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  icons_plus: ^4.0.0
  image_picker: ^1.0.5
  intl: ^0.18.1
  lottie: ^2.6.0
  mobile_scanner: ^3.5.7
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  quick_actions: ^1.0.6
  rename: ^3.0.1
  searchbar_animation: ^0.0.4
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  status_view: ^0.0.2
  timeago: ^3.6.0
  url_launcher: ^6.1.14
  uuid: ^4.2.2
  wolt_modal_sheet: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Icon_PNG_Selected/
    - assets/Icon_PNG_Unselected/
    - assets/Icon_SVG_Unselected/
    - assets/Icon_SVG_Unselected/
