name: connect_me
description: Connect_Me is a user-friendly mobile application that empowers
  users to streamline their communication, networking, and information-sharing
  processes with the power of QR codes. Whether you're a professional seeking to
  exchange business details, a social media enthusiast connecting with new
  friends, or a tech-savvy individual looking for a convenient way to share
  information, Connect_Me is the ultimate solution for all your QR code needs.
publish_to: "none"
version: 0.1.1+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  animated_custom_dropdown: ^2.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  clipboard: ^0.1.3
  cloud_firestore: ^4.13.5
  country_code_picker: ^3.0.0
  csc_picker: ^0.2.7
  dartz: ^0.10.1
  device_preview: ^1.1.0
  equatable: ^2.0.5
  firebase_analytics: ^10.7.4
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.6
  # flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.3.2
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  google_sign_in: ^6.1.6
  icons_plus: ^4.0.0
  image_cropper: ^5.0.1
  image_picker: ^1.0.5
  intl: ^0.18.0
  lottie: ^2.6.0
  mobile_scanner: ^3.5.7
  qr_flutter: ^4.1.0
  quick_actions: ^1.0.6
  recaptcha_enterprise_flutter: ^18.4.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  timeago: ^3.6.0
  url_launcher: ^6.1.14
  uuid: ^4.2.2
  vibration: ^1.8.4
  wolt_modal_sheet: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Icon_SVG_Unselected/
    - .env
  fonts:
    #kenia
    - family: Kenia
      fonts:
        - asset: font/Kenia/Kenia-Regular.ttf
        #Solway
    - family: Solway
      fonts:
        - asset: font/Solway/Solway-Bold.ttf
        - asset: font/Solway/Solway-ExtraBold.ttf
        - asset: font/Solway/Solway-Light.ttf
        - asset: font/Solway/Solway-Medium.ttf
        - asset: font/Solway/Solway-Regular.ttf
