// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCchftV552UUA0e9LkleEbY2SB0V3WqOn0',
    appId: '1:43256663922:web:6707f0da6b00b7897b17eb',
    messagingSenderId: '43256663922',
    projectId: 'connect-me-captured',
    authDomain: 'connect-me-captured.firebaseapp.com',
    storageBucket: 'connect-me-captured.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjycm5Vy7hetWHOEjTXk3-tM0ek3XmE_o',
    appId: '1:43256663922:android:ecf198699be0ff247b17eb',
    messagingSenderId: '43256663922',
    projectId: 'connect-me-captured',
    storageBucket: 'connect-me-captured.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJORtam-OBsLm_GwcerXOIKnmSv2IX01g',
    appId: '1:43256663922:ios:e631777a38b1ac127b17eb',
    messagingSenderId: '43256663922',
    projectId: 'connect-me-captured',
    storageBucket: 'connect-me-captured.appspot.com',
    iosBundleId: 'com.capturedHeart.connectMe',
  );
}
