on:
  pull_request:
    branches:
      - master
      - UI_build
  push:
    branches:
      - UI_build
      - master
name: "Build & Release"
jobs:
  build:
    name: Build & Release APK and IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "zulu"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.0"
          channel: "stable"
          cache: true
      - run: echo ${{ secrets.ENV_FILE }} | base64 -d > .env
      - run: echo ${{ secrets.FIREBASE_ANDROID_FILE }} | base64 -d > android/app/google-services.json
      - run: echo ${{ secrets.FIREBASE_IOS_FILE }} | base64 -d > ios/Runner/GoogleService-Info.plist
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v0.2.${{ github.run_number }}
          token: ${{ secrets.PUBLIC_KEY }}
